[package]
name = "flight-memory-validation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
wit-bindgen.workspace = true
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "flight:memory-validation"
